version: '3'

vars:
  SLEEP_CMD: '{{if eq .GOOS "windows"}}timeout{{else}}sleep{{end}}'

tasks:
  default:
    cmds:
      - task: test

  format:
    desc: Formats code
    cmds:
      - 'npm run format'

  test:
    desc: Run all tests
    deps: [format]
    cmds:
      - 'npm test'

  build:
    desc: Build application
    cmds:
      - 'npm build'

  start:
    desc: Start the application
    cmds:
      - 'npm start'

  sleep:
    desc: Sleeps for the given number of seconds
    vars:
      DURATION: '{{default 5 .DURATION}}'
    cmds:
      - '{{.SLEEP_CMD}} {{.DURATION}}'
